name: Deploy Lambda via Terraform

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Autorise le push sur la branche state

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Checkout state branch
        uses: actions/checkout@v4
        with:
          ref: state
          path: state_branch

      - name: Restore Terraform state
        run: |
          mkdir -p tfstate
          cp state_branch/tfstate/terraform.tfstate tfstate/terraform.tfstate || echo "No previous state found"
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Get API Gateway URL
        run: terraform output api_gateway_url

      - name: Test API Gateway
        run: |
          URL=$(terraform output -raw api_gateway_url)
          curl -X GET "$URL"
