name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Checkout state branch
        uses: actions/checkout@v4
        with:
          ref: state
          path: state_branch

      - name: Debug State Branch Contents
        run: |
          ls -la state_branch/tfstate/
          cat state_branch/tfstate/terraform.tfstate || echo "No state file found in state branch"

      - name: Restore Terraform state
        run: |
          mkdir -p ./tfstate
          cp state_branch/tfstate/terraform.tfstate ./tfstate/terraform.tfstate || echo "No previous state found"

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.6.0"

      - name: Terraform Init
        run: terraform init

      - name: Debug Terraform State Before Destroy
        run: cat ./tfstate/terraform.tfstate || echo "State file is missing"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
