name: Terraform Destroy

on:
  # Déclencheur manuel depuis l'interface GitHub
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Confirmer la destruction des ressources (true/false)'
        required: true
        default: 'false'
        type: boolean

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configuration de Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0" # Spécifiez la version de Terraform à utiliser

      # 3. Initialisation de Terraform
      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # 4. Validation des modifications (optionnel)
      - name: Terraform Plan
        run: terraform plan -destroy -out=tfplan

      # 5. Destruction des ressources
      - name: Terraform Destroy
        if: github.event.inputs.confirm_destroy == 'true' # Condition pour éviter des destructions accidentelles
        run: terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
